[10/03/24 05:22:01] INFO     INFO:root:Reading config from         config.py:114
                             'ts-3-5/cosmic-ray/test_3-5_0-8_257_p              
                             0/priority_queue1.toml'                            
                    INFO     INFO:cosmic_ray.commands.execute:Begi execute.py:45
                             nning execution                                    
                    INFO     INFO:cosmic_ray.testing:Running test  testing.py:37
                             (timeout=60.0): python -m pytest                   
                             --tb=no                                            
                             ./ts-3-5/test_3-5_0-8_257_p0.py                    
                    INFO     INFO:cosmic_ray.commands.execute:Job  execute.py:43
                             baseline complete                                  
                    INFO     INFO:cosmic_ray.commands.execute:Exec execute.py:53
                             ution finished                                     
                    ERROR    ERROR:root:Baseline failed. Execution    cli.py:161
                             with no mutation gives those following             
                             errors:                                            
                               >>> ============================= test           
                             session starts                                     
                             ==============================                     
                               >>> platform linux -- Python 3.10.12,            
                             pytest-8.3.3, pluggy-1.5.0                         
                               >>> rootdir:                                     
                             /home/lucca/teste/python_experiments2/pr           
                             iority-queue1                                      
                               >>> collected 5 items                            
                               >>>                                              
                               >>> ts-3-5/test_3-5_0-8_257_p0.py                
                             .F...                                              
                             [100%]                                             
                               >>>                                              
                               >>> =========================== short            
                             test summary info                                  
                             ============================                       
                               >>> FAILED                                       
                             ts-3-5/test_3-5_0-8_257_p0.py::test_remo           
                             ve_task - AssertionError: asse...                  
                               >>> ========================= 1                  
                             failed, 4 passed in 0.12s                          
                             ==========================                         
                               >>>                                              
